// Copyright 2026 The Bureau Authors
// SPDX-License-Identifier: Apache-2.0

package telemetry

import "github.com/bureau-foundation/bureau/lib/ref"

// ServiceStatus is the CBOR response for the telemetry service's
// unauthenticated "status" action. Contains only aggregate operational
// metrics — no fleet, machine, or source identifiers that could
// disclose topology.
type ServiceStatus struct {
	BatchesReceived      uint64          `cbor:"batches_received"`
	SpansReceived        uint64          `cbor:"spans_received"`
	MetricsReceived      uint64          `cbor:"metrics_received"`
	LogsReceived         uint64          `cbor:"logs_received"`
	OutputDeltasReceived uint64          `cbor:"output_deltas_received"`
	ConnectedRelays      int             `cbor:"connected_relays"`
	UptimeSeconds        float64         `cbor:"uptime_seconds"`
	ArtifactPersistence  bool            `cbor:"artifact_persistence"`
	LogManager           LogManagerStats `cbor:"log_manager"`
	Storage              StorageStats    `cbor:"storage"`
}

// StorageStats contains SQLite storage health metrics. Exposed via
// ServiceStatus so operators and agents can monitor database size,
// partition lifecycle, and record counts without direct database access.
type StorageStats struct {
	// PartitionCount is the number of active day partitions.
	PartitionCount int `cbor:"partition_count"`

	// OldestPartition is the YYYYMMDD suffix of the oldest partition,
	// or empty if no partitions exist.
	OldestPartition string `cbor:"oldest_partition,omitempty"`

	// NewestPartition is the YYYYMMDD suffix of the newest partition,
	// or empty if no partitions exist.
	NewestPartition string `cbor:"newest_partition,omitempty"`

	// DatabaseSizeBytes is the total size of the database file on
	// disk (page_count * page_size). Includes free pages.
	DatabaseSizeBytes int64 `cbor:"database_size_bytes"`

	// SpanCount is the total number of span records across all
	// active partitions.
	SpanCount int64 `cbor:"span_count"`

	// MetricCount is the total number of metric point records
	// across all active partitions.
	MetricCount int64 `cbor:"metric_count"`

	// LogCount is the total number of log records across all
	// active partitions.
	LogCount int64 `cbor:"log_count"`
}

// LogManagerStats contains operational counters for the log manager's
// output delta persistence pipeline. Exposed via ServiceStatus so
// operators and tests can verify the health of artifact storage and
// metadata writes.
type LogManagerStats struct {
	FlushCount     uint64 `cbor:"flush_count"`
	FlushErrors    uint64 `cbor:"flush_errors"`
	StoreCount     uint64 `cbor:"store_count"`
	StoreErrors    uint64 `cbor:"store_errors"`
	MetadataWrites uint64 `cbor:"metadata_writes"`
	MetadataErrors uint64 `cbor:"metadata_errors"`
	EvictionCount  uint64 `cbor:"eviction_count"`
	ActiveSessions int    `cbor:"active_sessions"`
	LastError      string `cbor:"last_error,omitempty"`
}

// CompleteLogRequest is the CBOR request for the telemetry service's
// "complete-log" action. Called by the daemon when a sandbox exits
// to flush remaining output and mark the log entity as complete.
//
// Source is required: the Matrix user ID of the principal whose
// sessions should be completed. The full user ID (not a bare
// localpart) is required for federation safety — localparts are
// only unique within a single homeserver.
//
// SessionID is optional: when set, completes only that specific
// session. When empty, completes ALL active sessions for the source.
// The daemon uses source-only (no session ID) because session IDs
// are generated by the launcher and not exposed through IPC.
type CompleteLogRequest struct {
	Source    ref.UserID `cbor:"source"`
	SessionID string     `cbor:"session_id,omitempty"`
}

// CompleteLogResponse is the CBOR response for the "complete-log"
// action. Completed is true if the session was flushed and
// transitioned to complete, or was already complete / never existed
// (idempotent).
type CompleteLogResponse struct {
	Completed bool `cbor:"completed"`
}

// ConfigureLogRequest is the CBOR request for the telemetry service's
// "configure-log" action. Called by the daemon after sandbox creation
// to set a per-source eviction limit based on the template's
// OutputCapture.MaxSize. The telemetry service stores this limit and
// uses it instead of the global default when evicting chunks for
// sessions from this source.
//
// Source is required: the Matrix user ID of the principal. The full
// user ID (not a bare localpart) is required for federation safety.
//
// MaxBytesPerSession is the maximum stored output in bytes before
// the eviction loop starts removing old chunks from the front.
// Must be positive.
type ConfigureLogRequest struct {
	Source             ref.UserID `cbor:"source"`
	MaxBytesPerSession int64      `cbor:"max_bytes_per_session"`
}

// ConfigureLogResponse is the CBOR response for the "configure-log"
// action. Configured is true if the per-source limit was stored
// successfully.
type ConfigureLogResponse struct {
	Configured bool `cbor:"configured"`
}
