// Copyright 2026 The Bureau Authors
// SPDX-License-Identifier: Apache-2.0

package schema

import (
	"encoding/json"

	"github.com/bureau-foundation/bureau/lib/ref"
	"github.com/bureau-foundation/bureau/lib/schema/pipeline"
)

// Matrix m.room.message msgtype constants for Bureau command messages.
// Commands are regular m.room.message events with custom msgtypes (not
// state events). The daemon receives them via /sync timeline events and
// posts threaded replies with the result.
const (
	// MsgTypeCommand is the msgtype for command request messages.
	// Commands are m.room.message events with structured fields for
	// the daemon to parse: command name, workspace target, parameters.
	// The human-readable body field allows the command to display
	// legibly in any Matrix client.
	MsgTypeCommand = "m.bureau.command"

	// MsgTypeCommandResult is the msgtype for command result messages.
	// Posted as threaded replies to the original command message.
	// Contains structured result data alongside a human-readable body
	// for display in standard Matrix clients.
	MsgTypeCommandResult = "m.bureau.command_result"
)

// CommandMessage is the parsed content of an m.bureau.command message.
// Commands are posted by the CLI to workspace rooms or config rooms,
// and the daemon processes them via /sync. The human-readable Body
// field ensures commands display legibly in any Matrix client.
type CommandMessage struct {
	// MsgType is the Matrix message type (always MsgTypeCommand for
	// incoming commands).
	MsgType string `json:"msgtype"`

	// Body is a human-readable representation of the command, shown
	// in standard Matrix clients (e.g., "workspace status iree/amdgpu/inference").
	Body string `json:"body"`

	// Command is the structured command name (e.g., "workspace.status",
	// "workspace.fetch", "principal.spawn").
	Command string `json:"command"`

	// Workspace is the target workspace for workspace-scoped commands
	// (e.g., "iree/amdgpu/inference"). Empty for global commands like
	// workspace.list.
	Workspace string `json:"workspace,omitempty"`

	// RequestID is an opaque identifier for correlating requests and
	// responses. The daemon includes it in the threaded result reply.
	// Generated by the CLI.
	RequestID string `json:"request_id,omitempty"`

	// SenderMachine identifies which machine the CLI is running on.
	// Informational — the daemon does not use this for routing.
	SenderMachine string `json:"sender_machine,omitempty"`

	// Parameters carries additional command-specific arguments. For
	// example, principal.spawn includes "template" and "payload"
	// fields. The daemon passes these through to the handler.
	Parameters map[string]any `json:"parameters,omitempty"`
}

// CommandResultMessage is the content of an m.room.message event with
// msgtype MsgTypeCommandResult. The daemon posts these as threaded replies
// to the original CommandMessage. The union of all fields covers three
// result shapes:
//
//   - Success: Status "success", Result contains command-specific payload
//   - Error: Status "error", Error contains the error message
//   - Pipeline result: Status "success"/"error", ExitCode and Steps from
//     the pipeline executor, optionally LogEventID for thread logging
//   - Accepted acknowledgment: Status "accepted", Principal names the
//     ephemeral executor principal (async commands like pipeline.execute)
//
// Fields not relevant to a particular result shape are omitted from JSON
// via omitempty.
type CommandResultMessage struct {
	MsgType    string                        `json:"msgtype"`
	Body       string                        `json:"body"`
	Status     string                        `json:"status"`
	Result     json.RawMessage               `json:"result,omitempty"`
	Error      string                        `json:"error,omitempty"`
	ExitCode   *int                          `json:"exit_code,omitempty"`
	DurationMS int64                         `json:"duration_ms"`
	Steps      []pipeline.PipelineStepResult `json:"steps,omitempty"`
	Outputs    map[string]string             `json:"outputs,omitempty"`
	LogEventID ref.EventID                   `json:"log_event_id,omitzero"`
	RequestID  string                        `json:"request_id,omitempty"`
	Principal  string                        `json:"principal,omitempty"`
	RelatesTo  *ThreadRelation               `json:"m.relates_to,omitempty"`
}

// ThreadRelation is the m.relates_to structure for threaded messages
// (MSC3440 / Matrix spec §11.10.1). Commands and their results are
// linked via this threading relation so that clients can render the
// request→response pair as a conversation thread.
type ThreadRelation struct {
	RelType       string      `json:"rel_type"`
	EventID       ref.EventID `json:"event_id"`
	IsFallingBack bool        `json:"is_falling_back,omitempty"`
	InReplyTo     *InReplyTo  `json:"m.in_reply_to,omitempty"`
}

// InReplyTo identifies the event being replied to within a thread
// relation. This is the fallback reply target for clients that do
// not support threads.
type InReplyTo struct {
	EventID ref.EventID `json:"event_id"`
}

// NewThreadRelation constructs a ThreadRelation for a threaded reply
// to the given event ID. This matches the structure the daemon uses
// when posting command results and pipeline results.
func NewThreadRelation(eventID ref.EventID) *ThreadRelation {
	return &ThreadRelation{
		RelType:       "m.thread",
		EventID:       eventID,
		IsFallingBack: true,
		InReplyTo: &InReplyTo{
			EventID: eventID,
		},
	}
}
