// Copyright 2026 The Bureau Authors
// SPDX-License-Identifier: Apache-2.0

package ref

import (
	"fmt"
	"strings"
)

// TicketID is a validated ticket identifier (e.g., "pip-a3f9", "tkt-12ab").
//
// Ticket IDs are generated by the ticket service as prefix-hexsuffix,
// where the prefix is an alphabetic string determined by ticket type
// and room configuration (e.g., "pip" for pipeline, "tkt" for general),
// and the suffix is a truncated SHA-256 hex hash. The dash separates
// prefix from suffix.
//
// TicketID is an immutable value type. The zero value is not valid;
// use IsZero to check.
type TicketID struct {
	id string
}

// ParseTicketID validates and wraps a raw ticket ID string. Returns
// an error if the string is empty or doesn't contain the required
// prefix-suffix structure (at least one character on each side of
// a '-' separator).
func ParseTicketID(raw string) (TicketID, error) {
	if raw == "" {
		return TicketID{}, fmt.Errorf("empty ticket ID")
	}
	dashIndex := strings.IndexByte(raw, '-')
	if dashIndex < 0 {
		return TicketID{}, fmt.Errorf("ticket ID missing '-' separator: %q", raw)
	}
	if dashIndex == 0 {
		return TicketID{}, fmt.Errorf("ticket ID has empty prefix: %q", raw)
	}
	if dashIndex == len(raw)-1 {
		return TicketID{}, fmt.Errorf("ticket ID has empty suffix: %q", raw)
	}
	return TicketID{id: raw}, nil
}

// MustParseTicketID is like ParseTicketID but panics on error. Use in
// tests and static initialization where the input is known-valid.
func MustParseTicketID(raw string) TicketID {
	t, err := ParseTicketID(raw)
	if err != nil {
		panic(fmt.Sprintf("ref.MustParseTicketID(%q): %v", raw, err))
	}
	return t
}

// String returns the full ticket ID string (e.g., "pip-a3f9").
func (t TicketID) String() string { return t.id }

// IsZero reports whether the TicketID is the zero value (uninitialized).
func (t TicketID) IsZero() bool { return t.id == "" }

// Prefix returns the ticket ID prefix (the part before the first '-').
// For example, "pip" for "pip-a3f9", "tkt" for "tkt-12ab".
func (t TicketID) Prefix() string {
	if t.id == "" {
		return ""
	}
	dashIndex := strings.IndexByte(t.id, '-')
	if dashIndex < 0 {
		return t.id
	}
	return t.id[:dashIndex]
}

// MarshalText implements encoding.TextMarshaler for JSON and other
// text-based serialization formats.
func (t TicketID) MarshalText() ([]byte, error) {
	if t.id == "" {
		return []byte{}, nil
	}
	return []byte(t.id), nil
}

// UnmarshalText implements encoding.TextUnmarshaler for JSON and other
// text-based serialization formats. Validates the ticket ID format.
// An empty input produces the zero value (unset ticket ID).
func (t *TicketID) UnmarshalText(data []byte) error {
	if len(data) == 0 {
		*t = TicketID{}
		return nil
	}
	parsed, err := ParseTicketID(string(data))
	if err != nil {
		return err
	}
	*t = parsed
	return nil
}
